### ISSUE TITLE
Rescale for future Vietnamese?

### ISSUE THREAD

**Issue by davelab6** [googlefonts/notable#1]
I pushed this to a staging server, and it looks a little large on the body:

<img width="1594" alt="screen shot 2018-08-20 at 19 00 38" src="https://user-images.githubusercontent.com/261579/44376299-b272d380-a4ac-11e8-97f0-6e2a981d1e39.png">

On the specimen page, I see that the caps are drawn to the upm, but I think this means there is no room for a Vietnamese extension in the future... 

![screencapture-fonts-sandbox-corp-google-specimen-notable-2018-08-20-19_08_34](https://user-images.githubusercontent.com/261579/44376284-a25af400-a4ac-11e8-89c3-c53a84b1ff91.png)

I wonder that it should be scaled down on the body, to look more like the size of text families' caps, and give it room for glyph set expansion without vertical metrics changes in future. 

@m4rc1e what do you think?

If you agree, we should also specify a fontbakery check for Felipe to implement that can catch this kind of thing.

**Comment by m4rc1e** [comment]
The cap height is 985 which is very tall for a 1000upm font. Ideally it should be ~700.

I didn't scale down because I suspect the designers have made their templates based on the font's proportions.
